{% set version = "2.0.0" %}

package:
  name: simhash
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/simhash/simhash-{{ version }}.tar.gz
  sha256: d486d44a1dde0245d0733b91c86d892e87a062c932a372d184f4d9ce970e2708

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - simhash

about:
  home: https://leons.im/posts/a-python-implementation-of-simhash-algorithm/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: This is a Python implementation of [Simhash](http://www.wwwconference.org/www2007/papers/paper215.pdf)

  dev_url: https://github.com/leonsim/simhash

extra:
  recipe-maintainers:
    - nikicc
    - primozgodec
