travis:
  secure:
    BINSTAR_TOKEN: u9xMIxnyZPQLwznA3rFRCwZof3ubtsjol8jtY/4MwGijKRpJ7HYSiKIZqx1XvVNQBICrZ27+5H9WfUYW1WdjNkCtIU3Nsike4qJ7RCGloxo6r5yCZAZSwR9J23V7tPpkFc7DFUvfnOq6hwDyKzG25U37O42H/2KIKpuyGm3HE0/dFly1sN4IaeKhRbyKcvhcZPlMm7kBGDsHW+ueyD14cRbl4FZ0BG4ZU5CpV0cKgRSQ1lcTLc2Ad5eboGkfCN+vfzuC4bhZXpunVqd/kQdQ9qZc0TYwd+Vy9WDVRQrtXGB0FBSYv5rZyHtwOSqA9Um5TgzEYtlOUF3b3UgMbfWJEgvwYsds5Dx5gkmFiJFMGkmuklFSHOrBmAZVCOwW0YwNixN1Ffr7HnihawdtSHgMbxlJ7qaxcrb/hsNO4WH6Zgt5/gBQCgEcsPc/RFYH01Num2vpK7XEt0urbJF9NVWtinMHDIUyu4mwfefJGa9PF54Aw3aWGe87Sm9H5UR9XsMepGJvw7if0xBs4oxBfYCh3tpDRZ4sCiHdo6D7ubMoFg6BKXjOpkfGOuxPkvnDrxb82YXxw3gZWi+1Rl31VpPrT3uDOmGiTVpbelNj5I9mRSEp5VD2fvgSbL6i6JxBjjISuasQWFnMk0hHVOuDkpWMzDn4DMZ1he6nLAxof3Wvo+4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
