travis:
  secure:
    BINSTAR_TOKEN: urfwrl/fO7QA6Bye8tWNt0jBhozGnYbzU+1UCaDbiaOLLvZFM29n4xX/YrWsKKjW0XfPT7dnA3Ue+LlUNeyupJuPr9YOR1MtCOsJM4zy+GeDn0A+hUPthcjG7JGnRTARFtsak6w2ws5gGONbBxB5hCCIP4zTq2ElDVd125Bk6O31m9VxAfNIQXuBcCJ0AOBWbFe6gD5M+Gzwk2Qi2ANTFZY5DV+AotFhFikzIg/+GKX0ssy7l7UO2SIy1BDya8gSDIbz2aT0Jh2AS7a/dzUTCURb5OZsNYLF0/NMtn5icthQgtHq1FO5x+ZSUmoI0cLkECpdCUUr6qk477FJG9eg0J+o4LMi0vpMBrGjBYCpFyS20TSQMlAx524z2NCG2s5UjW3n4eIfR6Rt63gcrv7hr8Bwoega6YNV8eA9oimAnNxoWweF7cZvmzqu5otbsSO1OlvRPRmcNMbuPFtA4bMkx/IphF0jsDeyEnEOfHs/PKMeJQtflCx19tSmJ2DGjHOIv+V4+KS6D+vMw66FLo2wGTlG8Yacm7oIwTJ206CICRmT8d71W0S7Ejo5Dt8rGacoZkSnCoTDrJY7aHZGtJXkugO8aeQPZrhxYIbZBqzXZbjp4eUYMOHsOGXUhOybIneB/HKNhOTCag1tL/l3WFhHiVOsfJGqrXTkXVL4ul0/+dA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
