travis:
  secure:
    BINSTAR_TOKEN: OxAnkUaXJMShbTzzruBszlRlZB3EX1PniduXsVxC7EFBFMnI5dRlStFxFEvsTuZJTRmvHUpFPJR87+XDnay1wAMu3lvZOwj65T3npXgdovxwetGEQRpYZ43lGU0Aohaw7pUR7R1miT11AqX8XLkylxn8D/8kxtAfmiQ0Cao29w+zaJAqN7vCQXioNVKqEpmIuDylzK1IK0n6MgS9zOncxVfRZhJUTtiCfrzYiXf0uYeTphBy0WYmQFExVaCRJRDXttJfPXZbyPkCUv//TcFfVvoUzmg9yW1jhTsNcsgzbOm6Wz8D9anWXBFbFssEW6cSr+Ynp7qupQ83u/Ds2/wSo6YdWKIRY3hZ79dcnT88MCv/bkQc78O6ESrnI86IOBTcVpNjioBmI7v3voQ7g1QiJYh2GlYND3m2afA+JbT8JD+NEOuPApjQB6XLA4tE/mDCo/TylKN0gtJ9nXpJupBIlze1+ubcaeGM4xnyuClzZt4wNh/f2gOTFLU2CUj8bCjkN3JjYQZSvQ8xd0xuoGw+xVqUd90CXISNYlQqo4ezsh9+QKosjYJ5KKDRVeWROgRHySKtUDlyThJ0SScrIMyLfKmGZ2LBUE6LlEBnIonFJ9xiwXJg9x3qfkYEbfhxOzwI0WcGAhThPGn2Yibi/T1aVWiOhMcTwHYfAKsjisIeaOU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
