travis:
  secure:
    BINSTAR_TOKEN: RvPP5Vzo7pqsg+LoZHX5hQGLMqaJv04Q+NfqDGy2ZUGs7fPgm69TjiZzZJ8h8jigXgTc7W0Rf0hmz47LX2bsDFs2ZDkSXmz/22hIGokdrsq9ypqw/EOvNmx+VKQ4/rHnOMgBVM3vXtC80Z0VNMMDInQmfjgYbgfAXYzL8p2W43d7fhMvg8xsHBuhd4cUmz6ganCIB5i9zOgFhspF9HPGYfYzEux3MyYk53y4JQ1jakdNNHuEBCe4RfjQvysBd+HOERtyAngo/y3mFU50T9lPaYDZAyq7H/VCWoZEKJC3McBDEPjRw1bM1iaADqmSqKcHSlHBHuaht2k8B33GHdU3J9ua3RY3vP324J1YxPz8be7z75vRS8LLKPc7s97X3r/+1pndpPiTahLfIUsH1MyDraUx64A6+8iGEwzECvbHB4tup1oSoQkeKqVBTtbVhslo8koDpr9Po6+nU/7Cye8gpUQAI0RyDbojK3JG6Ru2+0n/oWXGcochUgyuRbpFrfhZ7jIVaeO++ulftpdIPd/rwyI9x+A7QCGDyWUcqgjmMgEw3fk9UX4od5rf7YWLnO7hP6gT+iAu0m4QteOiy8EPwZArueRr4A2AbKO1ng+YhrJinbuzLFI1qualjrLAYCc2Jr8EZjykeX4yl/+W3MF+PQEHH7oUFl7aMFHd9DW+Pp8=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
