travis:
  secure:
    BINSTAR_TOKEN: z3zjtcdA14X127I2TW6U60BusGlq3thP6QjQRzPhh6AiwDdwvGvY6pDhWDr+wZ91Q9DLT4Pv8jUIKsJOM/EWNVf5BOcPuCfeOQr5DS0tOAxCfTZYfX+pPdVUZEeXT1pGSccx8pGNA8buOFB247APqDqxT5NfNPiD/8DT7tigfO1hNvMgNXt44UI1M0lVRDgh6o2axaOPElUwVh6PIItyvsXE4zj0dnoNc94uJChF2/HvXHHl56CySW9qHI2dDh01kk1gbUV6xK27c+HoSbXfCTgtHnPfL8lp09eTSqcXTrc4HVxA6Zz6ZLeDyrSdhXrL4ohY1crbHdS/5pNph217SF7+3G6zellH53GDK6RfyTR4LcCgaDbwc/JkwWH3IrBZBjFQX5Ov2E8Nf8yMyf1e809/mU4ptmsuySa1qUgyFMIT4gt/BTLFHSNpq06C5gwLj9CqG0xcfuAzIJzslVglviSTk2wx1um8LsTfCRgEcPMt1vTbc7ZtyLv7do0vRfjQza9IbmCcx9s7yLvSr2KQNyCHiqtNyW5HzPmd1bCcxeTK4jvSRrKbksr2srCsx/AiW0pbMkhdMNkx6lSy/fcq0HAPT/XJYuL0LqLRat0yk+YOnjG8nTu9wPYZ6/uYDvlr3dZlvuixEFKQGRSiYM1v5CvTZC4Uy9VOpVZH82tW0ZQ=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
